Add画面の作成 & テストデータの作成/表示
app-dojo-salon/LeanjoyFC-TodoApp pull request #10
Opened 2020-09-09 04:26 UTC by CatLuck2

## 今回行った作業の詳細を記入

ItemAddViewController（以下、ItemAddVC）の準備
- ItemAddVCのファイルと画面を作成
- ItemAddVCにUI（BarButtonItem,Label,TextField）を画面に設置、ファイルに紐付け
- ItemListVC <-> ItemAddVC間の遷移を実装（遷移、戻りの両方）

ItemAddVCからデータを受け渡し
- ItemAddVCでテストデータ（testCheckItem）を用意
- ItemAddVCのテストデータをItemListViewController（以下、ItemListVC）のitemDataに追加
- ItemListVCのitemDataをprintとtableViewで結果を確認

## レビューして欲しい内容

行っていただきたいのは、
- 「ItemListVC -> ItemAddVC -> 追加ボタンを押す -> ItemListVCに戻る -> print()、tableViewでテストデータがitemDataに追加」の動作確認をお願い致します。

## 勉強になったところ

## 躓いたところ

ItemAddVCのナビゲーションバーでCancelボタンが自動追加されなかったので、手動でBarButtonItemを追加しました。もし自動追加が可能なら、ご指摘をお願い致します。

2020-09-09 16:24 UTC, koji-torishima commented
storyboard分けても良いですね！
Storyboard Reference使って実装しればファイルは増えますが、何がどこに書いてあるのか分かりそうです。

2020-09-09 16:40 UTC, koji-torishima submitted a review, later dismissed

2020-09-09 16:40 UTC, koji-torishima commented on TodoApp/Views/Controllers/ItemListViewController.swift
> +    @IBAction func unwindToVC(_ unwindSegue: UIStoryboardSegue) {
segueでの値キャッチの実装にしたんですね！
動き的には問題なさそうです！

2020-09-09 16:40 UTC, koji-torishima commented on TodoApp/Views/Controllers/ItemListViewController.swift
> +            //printでの出力、tableViewでの表示、両方で追加されたかを確認
// のスペースを共通化しても良さそう！

2020-09-09 16:40 UTC, koji-torishima commented on TodoApp/Views/Controllers/ItemAddViewController.swift
> +    private(set) var testCheckItem = "test"
testとはいえこちらの実装はとても良いと思いました。
よく勉強されてますね！

2020-09-09 16:48 UTC, koji-torishima commented
>ItemAddVCのナビゲーションバーでCancelボタンが自動追加されなかったので、手動でBarButtonItemを追加しました。もし自動追加が可能なら、ご指摘をお願い致します。

多分手動でOKだと思います！

2020-09-09 16:56 UTC, koji-torishima requested changes
キャンセル処理未実装かな？

2020-09-10 01:56 UTC, CatLuck2 commented
改めてコミットしました!!

下記の項目に修正しましたので、ご確認よろしくお願いします。

- Add画面を別のStoryBoardで作成
- StoryBoardReferenceでItemListVC -> ItemAddVCを実装
- unWindToVCで項目追加時のみ処理するよう修正
- Cancelボタンでdismiss

2020-09-10 15:17 UTC, kodourhythm approved these changes
確認しました！勉強になります！

2020-09-11 06:08 UTC, miya1186 approved these changes
追加内容確認しました！

2020-09-11 14:14 UTC, syuu0227 approved these changes
動作確認しました！

2020-09-11 14:14 UTC, syuu0227 commented on TodoApp/Views/Controllers/ItemListViewController.swift
> +        // 追加ボタンを押下した場合
ここの追加ボタンというのは追加項目画面のSaveという認識で良いですかね？

2020-09-11 14:52 UTC, akio0911 commented on TodoApp/Views/Controllers/ItemAddViewController.swift
> +        performSegue(withIdentifier: "unWindByItemAdd", sender: nil)
`un wind` ではなく `unwind` という動詞だと思うので、こうかも。
```suggestion
        performSegue(withIdentifier: "unwindByItemAdd", sender: nil)
```
<img width="630" alt="image" src="https://user-images.githubusercontent.com/43180/92940137-b013b580-f489-11ea-8d71-bd661343554d.png">

2020-09-11 14:52 UTC, akio0911 commented on TodoApp/Views/Controllers/ItemListViewController.swift
> +        if unwindSegue.identifier == "unWindByItemAdd" {
ここも。
```suggestion
        if unwindSegue.identifier == "unwindByItemAdd" {
```

2020-09-11 14:52 UTC, akio0911 commented on TodoApp/Views/ItemAdd.storyboard
> +                        <segue destination="vok-sB-amB" kind="unwind" identifier="unWindByItemAdd" unwindAction="unwindToVC:" id="wHx-po-Rtl"/>
ここも。
```suggestion
                        <segue destination="vok-sB-amB" kind="unwind" identifier="unwindByItemAdd" unwindAction="unwindToVC:" id="wHx-po-Rtl"/>
```

2020-09-11 15:23 UTC, akio0911 commented
.DS_Store は .gitignore に追記した上で、git管理から外しちゃって良さそう

2020-09-11 17:02 UTC, koji-torishima commented on TodoApp/Views/Controllers/ItemAddViewController.swift
> +        performSegue(withIdentifier: "unWindByItemAdd", sender: nil)
@CatLuck2 ここだけ修正したほうが良さそうですね！！
修正したらまたお願いします！！

2020-09-12 00:13 UTC, CatLuck2 commented on TodoApp/Views/Controllers/ItemAddViewController.swift
> +        performSegue(withIdentifier: "unWindByItemAdd", sender: nil)
修正しました！

2020-09-12 00:13 UTC, CatLuck2 commented on TodoApp/Views/Controllers/ItemListViewController.swift
> +        if unwindSegue.identifier == "unWindByItemAdd" {
修正しました！

2020-09-12 00:14 UTC, CatLuck2 commented on TodoApp/Views/Controllers/ItemListViewController.swift
> +        // 追加ボタンを押下した場合
失礼しました。Save -> 追加、に文字を変更しました！
<img width="377" alt="スクリーンショット 2020-09-12 9 13 30" src="https://user-images.githubusercontent.com/43905123/92982264-4e2e6c80-f4d8-11ea-8147-7aed64520926.png">

2020-09-12 04:22 UTC, syuu0227 commented on TodoApp/Views/Controllers/ItemListViewController.swift
> +        // 追加ボタンを押下した場合
ありがとうございます！

2020-09-13 09:45 UTC, akio0911 commented on .gitignore
> +.DS_Store
👍🏻

2020-09-13 13:31 UTC, koji-torishima commented on .gitignore
> +.DS_Store
確認しました！！
ありがとうございます！！

2020-09-13 13:35 UTC, merged