Feature/issues 15
app-dojo-salon/LeanjoyFC-TodoApp pull request #24
Opened 2020-09-17 15:31 UTC by syuu0227

## 今回行った作業の詳細を記入

・CocoaPodsでRealmSwiftを追加
・Realmでの保存できることの確認

## レビューして欲しい内容

・Realmの導入方が正しくできているか

## 勉強になったところ

・Realmの導入、保存、受け取り方法

## 躓いたところ

・Realmの文法が分からず、エラーの対処に時間がかかった。

## 参考になった資料などあれば共有してください

・Realmを使ってTODOアプリを作ってみよう！/ Swift(Realmの使い方、初級編)
https://qiita.com/pe-ta/items/616e0dbd364179ca284b

## スクリーンショット(Before, After)

Before | After
------------- | -------------
<img src="" width="320"> | <img src="" width="320">

## その他

2020-09-17 20:34 UTC, koji-torishima requested changes

2020-09-17 20:34 UTC, koji-torishima commented on TodoApp/Views/Controllers/ItemListViewController.swift
> +    let itemModel = ItemModel()
この2つの定数はいらないと思います。
いらないというよりメソッド化したしても良いと思います。

2020-09-17 20:34 UTC, koji-torishima commented on TodoApp/Views/Controllers/ItemListViewController.swift
> +            let itemModel = ItemModel()
ここでも定義してしまっているので、どっちかにしましょう。

2020-09-17 20:34 UTC, koji-torishima commented on TodoApp/Views/Controllers/ItemListViewController.swift
> +            let itemModel = ItemModel()
別のfunctionを作って分けても良いと思います。
unwindToVC()のスコープの中にRealmの処理を書いてしまうと、ボタンのもつ機能の責務が多くなってしまいます。
おそらく、ここを押した時点でaddされてしまうというのは機能として違うと思います。

このボタンは、ItemAddViewControllerに遷移する機能を持っていますので、RealmにDataを保存する昨日ではないです。

Realmを操作する場合
ItemAddViewControllerのaddCheckItemの方に記載するのが良いかと思います。

2020-09-17 20:34 UTC, koji-torishima commented on TodoApp/Views/Controllers/ItemListViewController.swift
> +        let item: ItemModel = self.itemList[(indexPath as NSIndexPath).row]
ItemModelの型は指定しなくても良いです。
書き方としてはこれで良いです。
```swift
let item = itemList[indexPath.row]
```

2020-09-17 20:34 UTC, koji-torishima commented on TodoApp/Views/Controllers/ItemListViewController.swift
> +        itemList = realm.objects(ItemModel.self)
viewDidLoadにベタがきするのはなるべくやめていきましょう。
最初の頃はこれが当たり前のように本には書いてありますが、viewDidLoadが肥大化してしまうので、徐々に無くしていくと良いかと思われます。
参考資料
http://blog.penginmura.tech/entry/2018/02/12/163711

2020-09-17 20:34 UTC, koji-torishima commented on TodoApp/Models/items.swift
> +    @objc dynamic var name: String?
```Swift
class CheckListItem: Object {
   @objc dynamic var ItemName: String = "" 
   チェックマークのステータス: Bool = false
　登録した時間とかあるとより実践的ですね（今回はいらないですが）
}
````

2020-09-17 20:34 UTC, koji-torishima commented on TodoApp/Models/items.swift
> +    // RealmSwiftでの保存用のclass作成（takuma）
コメントはスコープの中ではなくClassの上の行あたりの方が良い気がしました。

2020-09-17 20:34 UTC, koji-torishima commented on TodoApp/Views/Controllers/ItemAddViewController.swift
こちらでRealmの追加処理を描きましょう。
-　TextFieldに入力したものをRealmに新規保存する

2020-09-17 20:34 UTC, koji-torishima commented on TodoApp/Views/Controllers/ItemListViewController.swift
>  final class ItemListViewController: UIViewController {
こちらの機能としては
- 読み込みしてList表示
- ステータスの変更
- delete処理
が主な機能となるので、
- realm.where
- realm.delate 
- realm.objects
この辺が必要になってきます。
参考資料
https://swift.hiros-dot.net/?page_id=515

2020-09-17 20:34 UTC, koji-torishima commented on Podfile
> +  pod 'RealmSwift'
LGTM!!!!!!!!

2020-09-17 20:36 UTC, koji-torishima commented
PRのタイトルが、
Feature/issues 15 となっておりますが、
issuesタイトルを記入していただけると良いと思います。

2020-09-18 01:35 UTC, akio0911 commented on TodoApp/Views/Controllers/ItemAddViewController.swift
> ・Realmでの保存できることの確認

とあったので、今回のPRの範囲は

1. Realmの導入と動作確認のみ
2. Realmを使った追加処理などの実装も含む

のいずれなのかを確認したさ

2020-09-18 01:47 UTC, koji-torishima commented on TodoApp/Views/Controllers/ItemAddViewController.swift
こちら決めた方が良さそうですね。
ありがとうございます。

2020-09-20 13:35 UTC, akio0911 commented on TodoApp/Views/Controllers/ItemListViewController.swift
> +    // テストデータを追加させるため、let->var、に変更  // 一旦使っていません。（takuma）
```suggestion
    // テストデータを追加させるため、let->var に変更  // 一旦使っていません。（takuma）
```

2020-09-20 15:04 UTC, koji-torishima approved these changes

2020-09-20 16:23 UTC, CatLuck2 approved these changes
レビューしました！

2020-09-21 07:21 UTC, syuu0227 commented
コンフリクト解消後のエラーですが、一旦退避案として、Realmの方のCheckListItemの名前をCheckListItem2にリネームしました。

2020-09-21 07:22 UTC, syuu0227 commented
それかRealm関連のものは一旦削除して、あとで追加という形にしますか？

2020-09-21 14:17 UTC, koji-torishima approved these changes

2020-09-21 14:17 UTC, merged